### ISSUE TITLE
Clipscore replication error: AttributeError: Can't pickle local object 

### ISSUE THREAD

**Issue by kathyli1** [jmhessel/clipscore#12]
After I install all the requirements and try to run the example usage line in the readme "python clipscore.py example/good_captions.json example/images/" I get this error: 

AttributeError: Can't pickle local object 'CLIPImageDataset._transform_test.<locals>.<lambda>
<img width="974" alt="Screenshot 2023-03-31 at 12 57 34 PM" src="https://user-images.githubusercontent.com/88126449/229183271-b302bad1-2a48-49f6-9c78-3c572df7fb36.png">

Please let me know if you have any advice!

**Comment by jmhessel** [comment]
you can disable multiprocessing in the dataloader to fix this I think; I don't quite know why this happens in your particular environment
