### ISSUE TITLE
Reproducing the results of the paper

### ISSUE THREAD

**Issue by PierreColombo** [jmhessel/clipscore#3]
Dear Authors, 
Thanks a lot for outsourcing the code and your great work. 

You mentionned a examples/eval.py but i cannot find it in your repo?

Do you plan to include the Flickr8K experiement as well ?
Thanks again for your paper and the code.
Kindest regards,
Pierre

**Comment by jmhessel** [comment]
Hi @PierreColombo ,

thanks for your interest in our work!

1) The example script you mentioned is actually in our second repo, which is here: https://github.com/jmhessel/pycocoevalcap . That repo is a fork of pycocoeval cap, which is the standard library used for mscoco caption evaluation. the same clipscore metric that can be computed in this repo can be computed there, but in that case, you can simply drop our fork of pycocoevalcap in as a replacement of the main version of pycocoevalcap. Either way should be fine.

2) As per your request, I added the code that replicates the flickr8k results (both expert and crowdflower) from the paper. For more details about the rationale for particular processing decisions, please see appendix A in the main paper.

For flickr8k-expert, the new code I added outputs:
```
bleu-4 Tau-c: 30.776
rouge Tau-c: 32.314
meteor Tau-c: 41.822
cider Tau-c: 43.891
spice Tau-c: 44.888
CLIPScore Tau-c: 51.444
RefCLIPScore Tau-c: 53.012
```

compare to the reported results (from the paper)
```
BLEU-4 30.8
ROUGE-L 32.3
METEOR 41.8
CIDEr 43.9
SPICE 44.9
CLIPScore 51.2
RefCLIPScore 53.0
```

compare to anderson et al 2016 --- we discuss our replication efforts + discrepancies with these results in the appendix in the paper.
```
Bleu-1 0.32
Bleu-4 0.14
ROUGE-L 0.32
METEOR 0.42
CIDEr 0.44
SPICE 0.45
```

For flickr8k- crowdflower, the new code I added outputs:
```
bleu-4 Tau-b: 16.863
rouge Tau-b: 19.903
meteor Tau-b: 22.269
cider Tau-b: 24.619
spice Tau-b: 24.425
CLIPScore Tau-b: 34.355
RefCLIPScore Tau-b: 36.417
```

compare to the results in the paper:
```
BLEU-4 16.9
ROUGE-L 19.9
METEOR 22.2
CIDEr 24.6
SPICE 24.4
CLIPScore 34.4
RefCLIPScore 36.4
```

Everything matches almost perfectly. The biggest discrepancy is, for CLIPScore on flickr8k expert, the new code appears to be getting around .2 tau-c _better_ than reported in the paper --- I don't have time to track down exactly why this discrepancy is happening (I suspect something to do with float16), but hopefully this is enough to get you started.


Jack

**Comment by jmhessel** [comment]
See: https://github.com/jmhessel/clipscore/tree/main/flickr8k_example

(also tagging @danieldeutsch in case this is useful !)
