### ISSUE TITLE
PASCAL-50S

### ISSUE THREAD

**Issue by zerocstaker** [jmhessel/clipscore#5]
Hi, Thank you so much for your awesome work!

I am wondering if you have the dataset and instructions/script to set up the PASCAL-50S dataset by any chance? The link to the annotation and original data on the official webpage does not work anymore.

Thanks,
David

**Comment by jmhessel** [comment]
Hi @zerocstaker --- which download isn't working for you? The original site seems to be up for me (http://vrama91.github.io/cider/)

By the way, those results were recently updated in the CLIPScore paper (https://github.com/jmhessel/clipscore/issues/4 --- which also contains some code illustrating the standard setup)

**Comment by zerocstaker** [comment]
Hi thanks for the reply. The website is up, but I get 404 when I try to download the [datset](https://filebox.ece.vt.edu/%7Evrama91/CIDEr_miscellanous/cider_datasets.tar)) and [consensus](https://filebox.ece.vt.edu/%7Evrama91/CIDEr_miscellanous/pyCIDErConsensus.zip), which I assume are necessary for getting it to work.

Thanks for the pointer, I will definitely follow the code provided.

**Comment by jmhessel** [comment]
I'm getting the 404 as well. Can you contact the authors of that work to let them know?

In the meantime, I fortunately was able to dig up a copy of those two files. here are some google drive links that I am hosting should work.

pyCIDErConsensus.zip:
https://drive.google.com/file/d/1sTE3ncliXONYWJ6PnoRoAmfDhQ30W2dD/view?usp=sharing

cider_datasets.tar
https://drive.google.com/file/d/1xfvfrTYpmJ_1aryxV1TI7Z2uvSxRYWnn/view?usp=sharing

**Comment by zerocstaker** [comment]
Thank you so much! I have already contacted the authors so hopefully they can update it soon!
