### ISSUE TITLE
Replicate results on composite dataset

### ISSUE THREAD

**Issue by zhuang-li** [jmhessel/clipscore#7]
Hi I downloaded composite dataset from https://imagesdg.wordpress.com/image-to-scene-description-graph/ as your instruction. 

But I found that their human annotation includes two types, thoroughness and relevance. May I ask which score you were using to calculate the correlation between human judgement and CLIPscore? Thank you!

**Comment by jmhessel** [comment]
thanks for your interest in our work! I believe we have tried both in the past, but the main results are for a key called "correctness".

**Comment by zhuang-li** [comment]
Thank you!

**Comment by zhuang-li** [comment]
@jmhessel hi Sorry to bother you again. I got another question. In the correctness file, the composite data usually includes only 3 or 4 captions rated by humans per image. So which one do you consider as the candidate, and which ones do you consider as the reference?

I am thinking of using one of the captions as the candidate and the rest as the reference, but this does not make sense because some captions have very low scores. I don't think the low-scored captions can be considered ground-truth references.

**Comment by jmhessel** [comment]
hi @zhuang-li  --- I don't have time at the moment to fully dive in the details because I'm travelling, but did you check out section 4.1 and Appendix A in the paper? they have a lot of details about the composite corpus, some replication efforts we undertook to match prior work, etc.

**Comment by bigbrother001** [comment]
Have you solved this problem? It is also confusing me to find the reference.
