### ISSUE TITLE
How to replicate the COCO challenge result?

### ISSUE THREAD

**Issue by zhuang-li** [jmhessel/clipscore#9]
Hi I tried to replicate the result on the dev set of the coco 2015 challenge. But I could not find the corresponding dataset and their human annotations. Can you pinpoint me to the location of the dataset? Thank you for the help!

**Comment by jmhessel** [comment]
Hi Zhuang,

Thanks for reaching out and for your interest in our work. If you go to this website and click "challenge2015" the data will be in a table. We have an appendix in the paper describing our thoughts about this particular assessment and why it's likely outlived its utility.

https://cocodataset.org/#captions-leaderboard

Jack
